version: '3.9'

services:

  db:
    image: postgis/postgis:15-3.3
    restart: always
    ports: 
      - 5455:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:




#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
#     container_name: elasticsearch
#     environment:
#       - node.name=es-node
#       - discovery.type=single-node
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#       - xpack.security.enabled=false
#     ports:
#       - "9200:9200"
#       - "9300:9300"
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     networks:
#       - esnet

#   kibana:
#     image: docker.elastic.co/kibana/kibana:8.8.2
#     container_name: kibana
#     environment:
#       ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch
#     networks:
#       - esnet


# volumes:
#   esdata:

# networks:
#   esnet: